<?php
/**
 * Файл русской локализации модуля ms.dobrozhil
 *
 * @package Ms\Dobrozhil
 * @author Mikhail Sergeev <msergeev06@gmail.com>
 * @copyright 2018 Mikhail Sergeev
 */

return array (
	'table_title' => 'Классы',
	'class_name' => 'Имя класса',
	'class_title' => 'Название класса на языке системы',
	'class_note' => 'Краткое описание класса',
	'class_parent_class' => 'Родительский класс',
	'class_parent_list' => 'Список родителей класса',
	'class_children_list' => 'Список потомков класса',
	'class_module' => 'Модуль, который добавил класс',
	'class_namespace' => 'Путь для создания объекта класса',
	'class_type' => 'Тип класса ("U" - пользовательский, "P" - программный)',
	'class_hidden' => 'Флаг скрытого из общего списка класса',
	'class_created_by' => 'ID пользователя создавшего класс',
	'class_created' => 'Дата создания класса',
	'class_updated_by' => 'ID пользователя изменившего параметры класса',
	'class_updated' => 'Дата последнего редактирования класса',
	'class_left_margin' => 'Левая граница',
	'class_right_margin' => 'Правая граница',
	'class_depth_level' => 'Уровень вложенности',

	'title_c_system' => 'Системы Умный дом',
	'note_c_system' => 'Класс систем Умного дома',
	'title_c_rooms' => 'Комнаты',
	'note_c_rooms' => 'Класс комнат дома',
	'title_c_users' => 'Пользователи системы',
	'note_c_users' => 'Класс пользователей системы',
	'title_c_system_states' => 'Статусы системы',
	'note_c_system_states' => 'Класс системных статусов',
	'title_c_operation_modes' => 'Режимы работы',
	'note_c_operation_modes' => 'Класс режимов работы',

	'title_c_darkness_mode' => 'Режимы работы Сумерки',
	'note_c_darkness_mode' => 'Класс режимов работы Сумерки',
	'title_c_cinema_mode' => 'Режимы работы Кино',
	'note_c_cinema_mode' => 'Класс режимов работы Кино',
	'title_c_eco_mode' => 'Режимы работы Экономичный',
	'note_c_eco_mode' => 'Класс режимов работы Экономичный',
	'title_c_guests_mode' => 'Режимы работы Гости',
	'note_c_guests_mode' => 'Класс режимов работы Гости',
	'title_c_night_mode' => 'Режимы работы Ночь',
	'note_c_night_mode' => 'Класс режимов работы Ночь',
	'title_c_nobody_home_mode' => 'Режимы работы Никого нет дома',
	'note_c_nobody_home_mode' => 'Класс режимов работы Никого нет дома',
	'title_c_security_armed_mode' => 'Режимы работы Охрана',
	'note_c_security_armed_mode' => 'Класс режимов работы Охрана',


	'title_c_devices' => 'Устройства',
	'note_c_devices' => 'Класс устройств',
	'title_c_devices_composite' => 'Составные устройства',
	'note_c_devices_composite' => 'Класс составных устройств',
	'title_c_devices_switches' => 'Выключатели',
	'note_c_devices_switches' => 'Класс выключатлей',
	'title_c_devices_dimmers' => 'Диммеры',
	'note_c_devices_dimmers' => 'Класс диммеров',
	'title_c_devices_buttons' => 'Кнопки',
	'note_c_devices_buttons' => 'Класс кнопок',
	'title_c_devices_controlled_relays' => 'Управляемые реле',
	'note_c_devices_controlled_relays' => 'Класс управляемых реле',
	'title_c_devices_sensors' => 'Датчики',
	'note_c_devices_sensors' => 'Класс датчиков',
	'title_c_devices_sensors_atmospheric_pressure' => 'Датчики атмосферного давления',
	'note_c_devices_sensors_atmospheric_pressure' => 'Класс датчиков атмосферного давления',
	'title_c_devices_sensors_humidity' => 'Датчики влажности',
	'note_c_devices_sensors_humidity' => 'Класс датчиков влажности',
	'title_c_devices_sensors_fluid_pressure' => 'Датчики давления жидкости',
	'note_c_devices_sensors_fluid_pressure' => 'Класс датчиков давления жидкости',
	'title_c_devices_sensors_motion' => 'Датчики движения',
	'note_c_devices_sensors_motion' => 'Класс датчиков движения',
	'title_c_devices_sensors_rain' => 'Датчики дождя',
	'note_c_devices_sensors_rain' => 'Класс датчиков дождя',
	'title_c_devices_sensors_smoke' => 'Датчики дыма',
	'note_c_devices_sensors_smoke' => 'Класс датчиков дыма',
	'title_c_devices_sensors_temperature' => 'Датчики температуры',
	'note_c_devices_sensors_temperature' => 'Класс датчиков температуры',
	'title_c_devices_sensors_flame' => 'Датчики пламени',
	'note_c_devices_sensors_flame' => 'Класс датчиков пламени',
	'title_c_devices_sensors_radiation' => 'Датчики радиационного фона',
	'note_c_devices_sensors_radiation' => 'Класс датчиков радиационного фона',
	'title_c_devices_sensors_water_level' => 'Датчики уровня воды',
	'note_c_devices_sensors_water_level' => 'Класс датчиков уровня воды',
	'title_c_devices_sensors_co2' => 'Датчики CO2',
	'note_c_devices_sensors_co2' => 'Класс датчиков co2',

);